config/routes.rb
Rails.application.routes.draw do
  resources :hashtags
  resources :clubs
  root to: 'clubs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
  has_and_belongs_to_many :hashtags
  # has_and_belongs_to_many doesn't support dependent options!!!! ...
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_and_belongs_to_many :clubs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
    
    hashtags = Hashtag.all
    @hashIds = hashtags.ids;
    @hashIds.shuffle!;
    @hashIds = @hashIds.slice(0..4)

    @randHashtags = Array.new();
    @hashIds.length.times do |i|
      @randHashtags << hashtags.where(id: @hashIds[i])[0]['hashtag'];
    end

  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
    @existHashtags = Array.new()
    @hashtagString = '';
    Club.find(@club['id']).hashtags.each_with_index do |tuple, i|
      @existHashtags << tuple['hashtag'];
      if(i == 0)
        @hashtagString += tuple['hashtag'];
      else
        @hashtagString += "," + tuple['hashtag'];
      end
    end
    @numOfHashTag = @existHashtags.length;
  end


  # POST /clubs
  # POST /clubs.json

  def create
    @club = Club.new(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end

    # < ----------------- hash tag start ----------------- >

    # new.html.erb로부터 전달받은 해시태그 스트링을 파싱하여 해시태그 테이블에 넣는다.
    # Hashtag = ApplicationRecord::Hashtag
    # 파싱
    hashtags = params[:hashTags].split(",");
    hashtags.each do |hashtag|
      # 해시태그가 테이블에 이미 존재하면 해시태그를 추가하지 않고 존재하는 해시태그의
      # id를 전달받아 join table에 두 foreign key 저장
      if(Hashtag.exists?(hashtag: hashtag))
        tmpHashtagId = Hashtag.where(hashtag: hashtag)[0]['id'];
        Club.find(@club['id']).hashtags << Hashtag.find(tmpHashtagId);
      # 해시태그가 테이블에 존재하지 않으면 해시태그를 테이블에 추가한 뒤
      # 추가한 해시태그의 id를 전달받아 join table에 두 foreign key 저장
      else
        hashNew = Hashtag.new();
        hashNew['hashtag'] = hashtag;
        hashNew.save;

        Club.find(@club['id']).hashtags << Hashtag.find(hashNew['id']);
      end
    end

    # < ----------------- hash tag end ----------------- >

  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end


    # < ----------------- hash tag start ----------------- >

    # delete all past hashtag
    @club.hashtag_ids.each do |hashtag_id|
      @club.hashtag_ids -= [hashtag_id];
    end

    # delete hashtag no clubs have --> but i think this function has high overheads
    # because of traverse over other databases each
    clubIds = Club.ids;
    joinTableHashIdx = Array.new();
    clubIds.each do |clubId|
      ######## get HashIds from ClubId
      ######## use this logic samely when club lists from a hash link!
      joinTableHashIdx += Club.find(clubId).hashtag_ids
    end
    joinTableHashIdx.uniq!
    Hashtag.where.not(id: joinTableHashIdx).destroy_all;



    hashtags = params[:hashTags].split(",");
    hashtags.each do |hashtag|

      if(Hashtag.exists?(hashtag: hashtag))
        tmpHashtagId = Hashtag.where(hashtag: hashtag)[0]['id'];
        Club.find(@club['id']).hashtags << Hashtag.find(tmpHashtagId);
      else
        hashNew = Hashtag.new();
        hashNew['hashtag'] = hashtag;
        hashNew.save;

        Club.find(@club['id']).hashtags << Hashtag.find(hashNew['id']);
      end
    end
    # < ----------------- hash tag end ----------------- >

  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy

    # < ----------------- hash tag start ----------------- >

    # destroy hashtags that the club has before the club removed from db
    @club.hashtag_ids.each do |hashtag_id|
      @club.hashtag_ids -= [hashtag_id];
    end

    clubIds = Club.ids;
    joinTableHashIdx = Array.new();
    clubIds.each do |clubId|
      joinTableHashIdx += Club.find(clubId).hashtag_ids
    end
    joinTableHashIdx.uniq!
    Hashtag.where.not(id: joinTableHashIdx).destroy_all;
    # < ----------------- hash tag end ----------------- >

    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def hashtag

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :desc)
    end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    hashId = params[:id];
    @Hashtag = Hashtag.find(hashId);
    @clubIdsForEachHash = Hashtag.find(hashId).club_ids.uniq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/views/clubs/_form.html.erb
<%= form_with(model: club, local: true) do |form| %>
  <% if club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<script>
var vacancy = new Array();
var numOfHashTag = parseInt('<%= @numOfHashTag%>');
console.log(typeof numOfHashTag);

function addHashTag(event) {
  if(numOfHashTag > 4) {
    // alert -> can't exceed 5 tags
  } else {

    if(event.keyCode == 13) {
      var value = document.getElementById('hashText').value;
      var buff = document.getElementById('hashtagBuff').value;

      for(var i = numOfHashTag ; i < 5 ; i++) {
        if(!vacancy[i]) {
          document.getElementById("hashTagContainer")
          .innerHTML += "<button id=btn_" + i + " onclick=deleteHashTag(event)>"
          + value + "</button>";
          numOfHashTag++; vacancy[i] = 1;
          break;
        }
      }

      if(buff.length == 0) {
        document.getElementById('hashtagBuff').value += value;
      }
      else {
        document.getElementById('hashtagBuff').value += "," + value;
      }

      // empty text box
      // blank(empty), space and started with #, parsing, comma
      document.getElementById('hashText').value = "";
    }
  }
}

function deleteHashTag(event) {
  var btnId = event.target.id; // a string
  var idx = btnId.replace(/\D/g, '');
  idx = parseInt(idx);

  // console.log(event);
  // only when there are hashtags
  if(numOfHashTag > 0) {
    var btnToRemove = document.getElementById(btnId);
    var comma = (document.getElementById('hashtagBuff')
    .value.match(/,/g) || []).length

    // remove button
    btnToRemove.remove(btnToRemove.selectedIndex);

    numOfHashTag--;

    // change button number following removed button
    for(var i  = 0 ; i < numOfHashTag - idx ; i++)
      assignId( (idx + 1) + i , btnId);

    tmp = document.getElementById('hashtagBuff').value.split(",");
    tmp.splice(idx, 1);
    console.log("aaaa : " + tmp);
    //subtract

    document.getElementById('hashtagBuff').value = "";

    if(comma)
      document.getElementById('hashtagBuff').value = tmp[0];

    for(var i = 0 ; i < comma - 1 ; i++){
      document.getElementById('hashtagBuff').value += "," + tmp[i + 1];
      console.log(tmp);
    }
    vacancy[numOfHashTag] = 0; // -> must be modified
  }
}
// btnid = event.target.id
function assignId(nextIdNumber, btnId){
  var nextIdNumberStr = nextIdNumber.toString();
  var nextId = btnId.replace(/[0-9]/, nextIdNumberStr);

  document.getElementById(nextId).id =
  document.getElementById(nextId).id.replace(/[0-9]/, (nextIdNumber - 1).toString());
}

</script>

<%= form_with(model: @club, local: true) do |form| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this @club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <!-- hidden type input tag to pass the hashtag value without user's intervention-->
  <input id="hashtagBuff" type="hidden" name="hashTags" value="<%=@hashtagString%>">
  <!-- hidden -->


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<!--  -->



<input id="hashText" type="text" placeholder="#HashTag" onKeyDown="addHashTag(event);">

<!-- Hashtag Container Start -->
<div id="hashTagContainer">
  <% @existHashtags.each_with_index do |existHashtag, i| %>
    <button id=btn_<%= i %> onclick=deleteHashTag(event)> <%= existHashtag%> </button>
  <% end %>

</div>
<!-- Hashtag Container End -->

<br/>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Clubs</h1>

<% @randHashtags.each_with_index do |randHashtag, i| %>
  <%= link_to randHashtag, hashtag_path(:id => @hashIds[i]) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= club.desc %></td>
        <td><%= link_to 'Show', club %></td>
        <td><%= link_to 'Edit', edit_club_path(club) %></td>
        <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Club', new_club_path %>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<script>
var vacancy = new Array()
var numOfHashTag = 0;

function addHashTag(event) {
  if(numOfHashTag > 4) {
    // alert -> can't exceed 5 tags
  } else {

    if(event.keyCode == 13) {
      var value = document.getElementById('hashText').value;
      var buff = document.getElementById('hashtagBuff').value;

      for(var i = 0 ; i < 5 ; i++) {
        if(!vacancy[i]) {
          document.getElementById("hashTagContainer")
          .innerHTML += "<button id=btn_" + i + " onclick=deleteHashTag(event)>"
          + value + "</button>";
          numOfHashTag++; vacancy[i] = 1;
          break;
        }
      }

      if(buff.length == 0) {
        document.getElementById('hashtagBuff').value += value;
      }
      else {
        document.getElementById('hashtagBuff').value += "," + value;
      }

      // empty text box
      // blank(empty), space and started with #, parsing, comma
      document.getElementById('hashText').value = "";
    }
  }
}

function deleteHashTag(event) {
  var btnId = event.target.id; // a string
  var idx = btnId.replace(/\D/g, '');
  idx = parseInt(idx);

  // console.log(event);
  // only when there are hashtags
  if(numOfHashTag > 0) {
    var btnToRemove = document.getElementById(btnId);
    var comma = (document.getElementById('hashtagBuff')
    .value.match(/,/g) || []).length

    // remove button
    btnToRemove.remove(btnToRemove.selectedIndex);

    numOfHashTag--;

    // change button number following removed button
    for(var i  = 0 ; i < numOfHashTag - idx ; i++)
      assignId( (idx + 1) + i , btnId);

    tmp = document.getElementById('hashtagBuff').value.split(",");
    tmp.splice(idx, 1);
    console.log("aaaa : " + tmp);
    //subtract

    document.getElementById('hashtagBuff').value = "";

    if(comma)
      document.getElementById('hashtagBuff').value = tmp[0];

    for(var i = 0 ; i < comma - 1 ; i++){
      document.getElementById('hashtagBuff').value += "," + tmp[i + 1];
      console.log(tmp);
    }
    vacancy[numOfHashTag] = 0; // -> must be modified
  }
}
// btnid = event.target.id
function assignId(nextIdNumber, btnId){
  var nextIdNumberStr = nextIdNumber.toString();
  var nextId = btnId.replace(/[0-9]/, nextIdNumberStr);

  document.getElementById(nextId).id =
  document.getElementById(nextId).id.replace(/[0-9]/, (nextIdNumber - 1).toString());
}

</script>



<!--  -->



<%= form_with(model: @club, local: true) do |form| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this @club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_area :desc %>
  </div>

  <!-- hidden type input tag to pass the hashtag value without user's intervention-->
  <input id="hashtagBuff" type="hidden" name="hashTags">
  <!-- hidden -->


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<!--  -->



<input id="hashText" type="text" placeholder="#HashTag" onKeyDown="addHashTag(event);">

<!-- Hashtag Container Start -->
<div id="hashTagContainer"> </div>
<!-- Hashtag Container End -->

<br/>
<%= link_to 'Back', clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @club.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @club.desc %>
</p>

<p>
  <strong>
    <% @club.hashtags.each do |tuple| %>
      <%= link_to tuple['hashtag'], hashtag_path(:id => tuple['id']) %>   &nbsp;
    <% end %>
  </strong>
</p>


<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

app/views/hashtags/show.html.erb
<h1>Club list</h1>
<h1>Hashtag : <%= @Hashtag['hashtag'] %></h1><br/>

<% @clubIdsForEachHash.each do |clubId| %>
  <%= link_to Club.find(clubId).name, club_path(:id => clubId) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hashfunc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>